### ISSUE TITLE
Add support for dark mode

### ISSUE THREAD

**Issue by mystiquewolf** [rtfpessoa/diff2html#403]
### Step -1: Before filling an issue check out troubleshooting section

- Go to [README.md#Troubleshooting](https://github.com/rtfpessoa/diff2html#troubleshooting)

### Step 0: Describe your environment

- OS: Kubuntu 21.04
- diff2html version: 3.4.11
- Using diff2html directly or using diff2html-ui helper: Through [VS Code Diff Viewer extension](https://youtu.be/j9Qx-iU237s)
- Extra flags: **\_**

### Step 1: Describe the problem:
Feature request: Add support for dark mode via parameter and via `prefers-color-scheme`. Not sure if the latter can be done at this project or projects that use this project should detect the environment in some way and pass parameters.
#### Observed Results:
Dark mode not available in VS Code Diff viewer extension. https://github.com/caponetto/vscode-diff-viewer/issues/36

#### Expected Results:

- What did you expect to happen?
-- Dark mode happens.

**Comment by rtfpessoa** [comment]
This should not be hard to implement, is mostly a matter of doing some CSS work and making it work with the dark highlight.js themes. Feel free to send a PR.

**Comment by Angelk90** [comment]
@mystiquewolf , @rtfpessoa : Are there any news?

If I put a background for example dark to the body this happens.

<img width="1382" alt="Schermata 2022-03-08 alle 19 36 16" src="https://user-images.githubusercontent.com/20476002/157303317-734cbd75-ea0b-42ce-8323-32d11acf1839.png">

**Comment by mystiquewolf** [comment]
No news from me for now, i'm busy with other things, don't use this very frequently yet and lately I'm using light themes.

**Comment by Angelk90** [comment]
We hope @rtfpessoa can solve the problem.

**Comment by rtfpessoa** [comment]
No news on my side. It will probably need some more tweaks to work. Feel free to send a PR

**Comment by ananyf** [comment]
Hello @rtfpessoa 
Can you use this lib https://darkmodejs.learn.uno/

**Comment by rtfpessoa** [comment]
That does not seem like a great solution. The solution should be done at the css level of this project.

**Comment by ngjuping** [comment]
these are some colors i have used: (scss + vue, v-deep here means affect nested HTML elements)
```css
.dark. Code-diff::v-deep {
  .d2h-code-side-linenumber,
  .d2h-info {
    background-color: #272822;
    color: #d0d0d0;
  }
  span {
    color: #d0d0d0;
  }

  .d2h-del {
    background-color: #7d4e50;
  }

  del {
    background-color: #a07c7e;
  }
  .d2h-ins {
    background-color: #748a74;
  }

  ins {
    background-color: #177016;
  }
}
```

<img width="916" alt="Screenshot 2022-12-01 at 11 54 32 AM" src="https://user-images.githubusercontent.com/35101494/204962119-10b2a556-246b-4b89-8090-1c9d668c67c5.png">
