### ISSUE TITLE
Add support for sticky file headers

### ISSUE THREAD

**Issue by ericcornelissen** [rtfpessoa/diff2html#455]
On GitHub, as you scroll through the diff of e.g. a Pull Request, the filename sticks to the top of the screen:

[GitHub's sticky file header preview.webm](https://user-images.githubusercontent.com/3742559/198835778-b12a06e6-5d04-4dfa-a587-6bf052c0f588.webm)

This allows you to see what file you're looking at at all times.

I didn't spot any option ([1](https://github.com/rtfpessoa/diff2html/tree/59ff2956ab15452e1e323917fe01f901313b0fa8#diff2html-configuration), [2](https://github.com/rtfpessoa/diff2html/tree/59ff2956ab15452e1e323917fe01f901313b0fa8#diff2html-configuration)) to enable this, nor did I manage to find a previous issue requesting this feature.

I played around with this in a browser and I think it can be implemented (ignoring adding logic to support it as an option) by adding the following CSS:

```css
.d2h-file-header {
  /* rest of the css ... */

  /* make it sticky */
  position: sticky;
  top: 0;

  /* prevent UI glitch where line number appear over the header */
  z-index: 1;
}
```
